# filepath: /C:/Users/denis1/Desktop/Repos/Backup/Timetracker_frontend/eslint.yml
name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run lint || true
    - name: Upload ESLint results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: eslint-results.sarif